0.0.9 update
AnacondaRecipes/swagger-ui-bundle-feedstock pull request #1
Opened 2022-10-28 16:14 UTC by ViridianMelody

Upstream repo: https://github.com/dtkav/swagger_ui_bundle/tree/master
Jira Issue: https://anaconda.atlassian.net/browse/PKG-114
Source diff: https://github.com/dtkav/swagger_ui_bundle/compare/v0.0.8...v0.0.9

2022-10-28 16:15 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

WARNING: /tmp/abs_f46kbosmov/clone/recipe/meta.yaml:45: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

2022-10-28 16:55 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

WARNING: /tmp/abs_01f321gua8/clone/recipe/meta.yaml:45: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

2022-10-28 17:00 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

WARNING: /tmp/abs_ffzor_48km/clone/recipe/meta.yaml:45: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

2022-10-28 17:48 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

WARNING: /tmp/abs_b2581moekj/clone/recipe/meta.yaml:47: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

2022-10-28 20:43 UTC, Arishamays1 approved these changes
LGTM!

2022-10-28 22:01 UTC, ryanskeith requested changes
Look great.  Please see comments before merging.

2022-10-28 22:01 UTC, ryanskeith commented on abs.yaml
> +channels:
Please remove abs.yam before merging.

2022-10-28 22:01 UTC, ryanskeith commented on recipe/meta.yaml
>      - flake8
If you updated flake8 because of this, you should probably note the version necessary to make it work here.

2022-10-30 04:29 UTC, varlackc reviewed
While the earliest version of `python` that we support is `3.7`, the earliest `python` version supported in the upstream is `3.4`
https://github.com/dtkav/swagger_ui_bundle/blob/master/setup.py#L76

We might want to remove the quotes on the `home_url`
https://github.com/AnacondaRecipes/swagger-ui-bundle-feedstock/blob/234cbe59f69ec8003428e8ed1fb91aa542c657cd/recipe/meta.yaml#L38

2022-10-31 11:37 UTC, skupr-anaconda commented on recipe/meta.yaml
> +  sha256: "abebdbb77a7ffa91e46caca35212f5bd39028db9b0a45416b51215c5e7a1b3df"
Please remove quotes symbols `"`

2022-10-31 11:37 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - wheel
Also, missing setuptools, see https://github.com/dtkav/swagger_ui_bundle/blob/0657580c653ae1cb3829b28a72607712addd7019/setup.py#L8

2022-10-31 11:37 UTC, skupr-anaconda commented on recipe/meta.yaml
>    home: "https://github.com/dtkav/swagger_ui_bundle"
Please remove quotes `"`

2022-10-31 11:37 UTC, skupr-anaconda commented on recipe/meta.yaml
>    license_family: "APACHE"
Please remove quotes `"`

2022-10-31 11:37 UTC, skupr-anaconda commented on recipe/meta.yaml
>    license_file: "LICENSE"
quotes `"` are redundant

2022-10-31 16:24 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

WARNING: /tmp/abs_42cdztr9_v/clone/recipe/meta.yaml:48: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

2022-10-31 16:59 UTC, skupr-anaconda commented
@ViridianMelody It seems like `ERROR: Could not find a version that satisfies the requirement importlib-metadata<4.3 (from versions: none)` is caused by different versions of `importlib-metadata` for different `python` versions. In python 3.10 and 3.11 it's already in the standard library.
Try if this will help https://github.com/AnacondaRecipes/spyder-feedstock/blob/61d8f34cc93d0dcb8289c6fc0a4b097e4f7e09e6/recipe/meta.yaml#L72-L73

2022-10-31 17:03 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

WARNING: /tmp/abs_eabb98komk/clone/recipe/meta.yaml:51: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

2022-10-31 17:07 UTC, skupr-anaconda commented
It looks like Prefect has issues on win64 `PermissionError: [WinError 5] Access is denied: 'C:\\Users\\builder-admin\\AppData\\Local\\Temp\\pip-pip-egg-info-cfmruek1\\swagger_ui_bundle.egg-info\\dependency_links.txt'`

2022-10-31 17:10 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

WARNING: /tmp/abs_59cnfdz3jn/clone/recipe/meta.yaml:51: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

2022-10-31 18:00 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

WARNING: /tmp/abs_3bzx3hqelb/clone/recipe/meta.yaml:52: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

2022-10-31 18:07 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

WARNING: /tmp/abs_6c2s13kd3w/clone/recipe/meta.yaml:52: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

2022-10-31 20:27 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

WARNING: /tmp/abs_11c1ar0qk1/clone/recipe/meta.yaml:52: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

2022-11-01 15:22 UTC, ViridianMelody commented on abs.yaml
> +channels:
Done!

2022-11-01 15:22 UTC, ViridianMelody commented on recipe/meta.yaml
>      - flake8
Ended up not updating flake8 for now.

2022-11-01 19:14 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

WARNING: /tmp/abs_34jc2ot8eu/clone/recipe/meta.yaml:52: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

2022-11-02 08:32 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - mccabe >=0.6.0,<0.7.0
There was an inconsistency in the v0.6.1 artifacts on different platforms.
mccabe 0.7.0 is a noarch python package. It has minimal changes, see https://github.com/PyCQA/mccabe/compare/0.6.1...0.7.0. You can safely use it. That's why the pinning `mccabe >=0.6.0,<0.8.0` is OK.

2022-11-02 17:28 UTC, ViridianMelody commented on recipe/meta.yaml
> +    - mccabe >=0.6.0,<0.7.0
Using `mccabe >0.6.0, <0.8.0` causes the build to fail due to the mismatch with `flake8`'s metadata. `flake8` itself will build (as long as `pip check` is disabled), but not anything that depends on it.

2022-11-02 17:30 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - mccabe >=0.6.0,<0.7.0
Yeah, you can just comment `pip check` to disable it

2022-11-02 17:36 UTC, ViridianMelody commented on recipe/meta.yaml
> +    - mccabe >=0.6.0,<0.7.0
Here are the errors I was getting:
```
ERROR: Could not find a version that satisfies the requirement mccabe<0.7.0,>=0.6.0 (from versions: none)
ERROR: No matching distribution found for mccabe<0.7.0,>=0.6.0
```

2022-11-02 20:47 UTC, AndrewVallette commented on recipe/meta.yaml
> +    - mccabe >=0.6.0,<0.7.0
@skupr-anaconda You are correct that there are minimal changes in `0.7.0`, but going with `<0.8.0` means that future versions like `0.7.5` or `0.7.10` could potentially be used. And we do not yet know what changes would exist.

I believe the safest choice to use the `<0.7.0` pinning that Melody is using. This is aligned with what upstream is doing.

I should also ask, what are the inconsistencies that exist in `0.6.1`? Is it something that should truly cause us to use `0.7.0`? If so, using `<=0.7.0` is another option as well.

I'd prefer to stay go with the pinnings that upstream uses, and not skip `pip check`, unless there is a specific reason.

2022-11-03 07:49 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - mccabe >=0.6.0,<0.7.0
@AndrewVallette Yeah, you are right, <=0.7.0 will be the better pinning. It was a workaround to build flake8. At that time there were missing packages on some platforms. If now we can build with 0.6.1 for all python versions and all platforms we can try it

2022-11-04 18:23 UTC, ryanskeith approved these changes
LGTM

2022-11-04 21:01 UTC, merged

2022-11-04 21:02 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

WARNING: /tmp/abs_f0zq10lpz6/clone/recipe/meta.yaml:52: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found